# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'

# Binaries
brew 'awscli'
brew 'bash'
brew 'coreutils'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'gnu-sed'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'moreutils'
brew 'pkg-config'
brew 'svn' # needed to install fonts

# Development
brew 'bat'
brew 'exa'
brew 'fzf'
brew 'glances' # better `top`
brew 'imagemagick'
brew 'jq'
brew 'meilisearch'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'pure'
brew 'redis'
brew 'ripgrep'
brew 'shellcheck'
brew 'yarn'
