# frozen_string_literal: true

# Taps
tap 'hashicorp/tap'

# Binaries
brew 'bat'
brew 'eza'
brew 'gh'
brew 'go'
brew 'hashicorp/tap/terraform'
brew 'oven-sh/bun/bun'
brew 'pnpm'
brew 'pyenv'
brew 'ripgrep'
brew 'sqlite'
brew 'starship'
brew 'stow'
brew 'tflint'
